### ISSUE TITLE
１つのパッケージの複数のブランチからプログラムを取ることはできない

### ISSUE THREAD

**Issue by kochigami** [kochigami/walk_together#2]
```
- git:
    local-name: naoqi_bridge
    uri: http://github.com/kochigami/naoqi_bridge.git
    version: add-face-tracker-node-and-launch
- git:
    local-name: naoqi_bridge
    uri: http://github.com/kochigami/naoqi_bridge.git
    version: add-external-collision-avoidance
```
のように書くと，.rosinstallに書き込まれる時に上書きされて１つしか残らない

**Comment by kochigami** [comment]
```
- git:
    local-name: naoqi_bridge1
    uri: http://github.com/kochigami/naoqi_bridge.git
    version: add-face-tracker-node-and-launch
- git:
    local-name: naoqi_bridge2
    uri: http://github.com/kochigami/naoqi_bridge.git
    version: add-external-collision-avoidance
```
のように書くと，```rosdep install```の時に，
multiple packages found with the same name "naoqi_apps"のようなエラーが出る
